### ISSUE TITLE
No countdown

### ISSUE THREAD

**Issue by lentchr** [matasarei/block_countdown#1]
Hello 
I installed the plug in and tried a test for new year. I was able to set the block, but no countdown appears. What did I do wrong?
![countdown1](https://user-images.githubusercontent.com/33871140/33079350-a97a45ae-ced5-11e7-83f7-eb9e75e02623.JPG)
![countdown2](https://user-images.githubusercontent.com/33871140/33079405-c65750d6-ced5-11e7-8b67-b643eb9f3c9c.JPG)

Thanks for help
cl

**Comment by matasarei** [comment]
Hello. Please tell me what browser do you use and your Moodle version. And if you can please show me 
browser console / log. Or maybe you can provide URL?

**Comment by lentchr** [comment]
Hey there.
Im using IE 11, moodle version 3.3.1+. 
Can`t show console, URL probably won`t help (intern Plattform)...

**Comment by matasarei** [comment]
Seems this issue related to JS minifier, so I decided to replace jquery.countdown.js with proper minified version. Please check latest version from GitHub on your local project.

**Comment by lentchr** [comment]
Thanks a lot, now it works perfect!

**Comment by matasarei** [comment]
Cool! Thank you. New version will be available soon on Moodle repository.
