### ISSUE TITLE
custom styles not specific enough.

### ISSUE THREAD

**Issue by danmarsden** [matasarei/block_countdown#11]
custom block styles should all be prefixed with the block class so they do not clash with other site styles.

eg:
https://github.com/matasarei/block_countdown/blob/master/styles.css#L8

should be 
.block_countdown .countdown-daystext {

and there shouldn't be a comma at the end of this line:
https://github.com/matasarei/block_countdown/blob/master/styles.css#L1

**Comment by matasarei** [comment]
Hello @danmarsden ! 
Good suggest, except this one:

> and there shouldn't be a comma at the end of this line

Why do you think so? It is styles for both `block-countdown-timer` and `countdown-ended`. If you will check again you may notice that `countdown-ended` only shows when countdown is actually ended.

**Comment by danmarsden** [comment]
I probably didn't explain that well.

all the "styles.css" files get combined into a single css file for caching. when adding styles to your plugin you need to make sure the css is only targeting the content inside your block - this prevents your styles from being accidentally applied to items that are not inside your block - I haven't looked closely at how your styles are applied but maybe the first example I gave should be more like this:

.block_countdown block-countdown-timer,
.block_countdown .countdown-ended {

**Comment by matasarei** [comment]
I see your point, but `countdown-ended` is not a child of `block-countdown-timer` so in this case it makes no sense. But in general, you right and I'll update the plugin soon.

**Comment by danmarsden** [comment]
yeah - that was a typo in my first version above (edited now)- moving too quick :-)
