### ISSUE TITLE
missing strings for capabilities

### ISSUE THREAD

**Issue by danmarsden** [matasarei/block_countdown#12]
Invalid get_string() identifier: 'countdown:myaddinstance' or component 'block_countdown'. Perhaps you are missing $string['countdown:myaddinstance'] = ''; in blocks/countdown/lang/en/block_countdown.php?

also looks like "block/countdown:view" was accidentally added? - that isn't a normal block capability and I couldn't see it used in your code either.

**Comment by matasarei** [comment]
Hello @danmarsden ! Thank you for your review and feedback.

About `view` capability:
> that isn't a normal block capability

As I know it is normal and should work. For example, I can see the same in the default `lp` block:
https://github.com/moodle/moodle/blob/master/blocks/lp/db/access.php#L49

Of course, I can be wrong, so if you have prof about this one I will remove it.

**Comment by danmarsden** [comment]
I've never seen that before... I suspect it's a bug in the lp block because it's not in any of the others that I can see... I'll find out!

**Comment by matasarei** [comment]
@danmarsden please check my PR when you have time: https://github.com/matasarei/block_countdown/pull/13
Also I'll wait until you will know about the `view` capability.

**Comment by danmarsden** [comment]
yeah - that was incorrectly added to the lp block. Theoretically you could implement a "view" capabiltiy by checking it in the get_content() function but lp doesn't do that (and neither does yours.) - you could either remove the capability, or add the missing string for the capability and add a check in get_content to use the capability.

**Comment by matasarei** [comment]
Okay, thank you for explanation. PR updated.

**Comment by danmarsden** [comment]
np - I've created https://tracker.moodle.org/browse/MDL-64124 to help remind someone to fix the core lp block too.
