### ISSUE TITLE
Countdown block showing incorrect time remaining

### ISSUE THREAD

**Issue by emmarichardson** [matasarei/block_countdown#2]
We are using this block on moodleassociation.org site.  In one course, it works as expected.  The second timer that I have added (to a different course) is totally wrong and showing different time remaining for different users - I am suspecting a time zone issue.  It is almost as if it is adjusting for my computer time zone and adding hours to the timer to compensate.  I can create a log in for you if needed on the site to see this in action.

**Comment by matasarei** [comment]
Hello @emmarichardson. I'll check what can be wrong. Unfortunately I can't do it right now, but maybe on weekend.

**Comment by emmarichardson** [comment]
As far as I can tell, the block is adjusting for the computer time zone of the person seeing it which is exactly what we did not want to happen!  So, if I am in MST, the block will show me the time remaining until Mar 1, 8:00 AM MST but if I am in UTC the block will show me the time remaining until Mar 1, 8:00 AM UTC.  We need to be able to set it this to the time of the Moodle server and not have it change so that if I set it for Mar 1, 8:00 AM and the Moodle server time zone is UTC, it will show the same time remaining regardless of who looks at it.

**Comment by matasarei** [comment]
Please try this code: https://github.com/matasarei/block_countdown/archive/utc-test.zip (you can check changes here: https://github.com/matasarei/block_countdown/commit/f5e7071f1b3defcbe225f3e9273aa07ae5870cdb)

**Comment by matasarei** [comment]
@emmarichardson Please try this code: https://github.com/matasarei/block_countdown/archive/utc-test.zip (you can check changes here: https://github.com/matasarei/block_countdown/commit/2903ed7fb0c315bb4f15a3aedda3eb2bbbf11575)

**Comment by emmarichardson** [comment]
Thank you so much.  We are getting much closer.  The timezone is adjusting correctly and reading from Moodle.  But I cannot figure out exactly where it is pulling "time now” from as it appears to be consistently five hours off.  Of course, I am not sure that is the exact problem but it seems very strange that is five hours off on two different servers…I tried looking at the js file but nothing jumped out at me..

Emma



Emma Richardson
Distance Learning Coordinator
Direct: 719-771-4022

**Comment by emmarichardson** [comment]
The time just changed on me and is now showing correctly?  I am even more confused now on how it could change…is this referencing an outside source somehow?

Emma



Emma Richardson
Distance Learning Coordinator
Direct: 719-771-4022

**Comment by matasarei** [comment]
New version should work fine. Please check on your side.
